# Pushes the contents of the repo to the Codeberg mirror
name: ðŸªž Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '10 03 * * 0' # At 03:10 on Sunday
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:alicia/git-into-open-source.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
